//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoProjectWPF.RepService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RepService.IRepositoryService")]
    public interface IRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryService/Save", ReplyAction="http://tempuri.org/IRepositoryService/SaveResponse")]
        void Save(CommonLibrary.Model.Car obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryService/Save", ReplyAction="http://tempuri.org/IRepositoryService/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(CommonLibrary.Model.Car obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepositoryServiceChannel : AutoProjectWPF.RepService.IRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepositoryServiceClient : System.ServiceModel.ClientBase<AutoProjectWPF.RepService.IRepositoryService>, AutoProjectWPF.RepService.IRepositoryService {
        
        public RepositoryServiceClient() {
        }
        
        public RepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Save(CommonLibrary.Model.Car obj) {
            base.Channel.Save(obj);
        }
        
        public System.Threading.Tasks.Task SaveAsync(CommonLibrary.Model.Car obj) {
            return base.Channel.SaveAsync(obj);
        }
    }
}
